### ISSUE TITLE
error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by glorykakessa** [thecartercenter/nemo#971]
When trying to send broadcast message, we reveive the following error : 

SSL_connect returned=1 errno=0 peeraddr=34.199.90.57:443 state=error: certificate verify failed (unable to get local issuer certificate)
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:46:in `connect_nonblock'

-------------------------------
Backtrace:
-------------------------------

  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:46:in `connect_nonblock'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:46:in `ssl_socket_connect'
  /home/deploy/.rbenv/versions/3.1.4/lib/ruby/3.1.0/net/http.rb:1089:in `connect'
  /home/deploy/.rbenv/versions/3.1.4/lib/ruby/3.1.0/net/http.rb:995:in `do_start'
  /home/deploy/.rbenv/versions/3.1.4/lib/ruby/3.1.0/net/http.rb:984:in `start'
  /home/deploy/.rbenv/versions/3.1.4/lib/ruby/3.1.0/net/http.rb:1564:in `request'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-5.10.0/lib/sentry/net/http.rb:29:in `request'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/net_http.rb:64:in `block in request'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/scout_apm-5.3.5/lib/scout_apm/tracer.rb:34:in `instrument'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/scout_apm-5.3.5/lib/scout_apm/tracer.rb:44:in `instrument'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/net_http.rb:63:in `request'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/twilio-ruby-4.13.0/lib/twilio-ruby/rest/base_client.rb:109:in `connect_and_send'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/twilio-ruby-4.13.0/lib/twilio-ruby/rest/base_client.rb:55:in `block (2 levels) in <class:BaseClient>'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/twilio-ruby-4.13.0/lib/twilio-ruby/rest/list_resource.rb:94:in `create'
  /home/deploy/nemo/app/models/sms/adapters/twilio_adapter.rb:97:in `send_message'
  /home/deploy/nemo/app/models/sms/adapters/twilio_adapter.rb:81:in `block in send_message_for_each_recipient'
  /home/deploy/nemo/app/models/sms/adapters/twilio_adapter.rb:80:in `each'
  /home/deploy/nemo/app/models/sms/adapters/twilio_adapter.rb:80:in `each_with_index'
  /home/deploy/nemo/app/models/sms/adapters/twilio_adapter.rb:80:in `send_message_for_each_recipient'
  /home/deploy/nemo/app/models/sms/adapters/twilio_adapter.rb:36:in `deliver'
  /home/deploy/nemo/app/models/sms/broadcaster.rb:15:in `deliver'
  /home/deploy/nemo/app/models/broadcast.rb:136:in `deilver_smses_and_return_any_errors'
  /home/deploy/nemo/app/models/broadcast.rb:82:in `deliver'
  /home/deploy/nemo/app/jobs/broadcast_operation_job.rb:7:in `perform'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:48:in `block in perform_now'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  /home/deploy/nemo/app/models/setting.rb:68:in `with_cache'
  /home/deploy/nemo/app/jobs/application_job.rb:7:in `block in <class:ApplicationJob>'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/instrumentation.rb:21:in `block in instrument'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:203:in `block in instrument'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:203:in `instrument'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/instrumentation.rb:31:in `instrument'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/logging.rb:22:in `block in tag_logger'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:37:in `tagged'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:99:in `tagged'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/logging.rb:22:in `tag_logger'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:47:in `perform_now'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/sentry-rails-5.10.0/lib/sentry/rails/active_job.rb:9:in `block in perform_now'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/sentry-rails-5.10.0/lib/sentry/rails/active_job.rb:35:in `block in record'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-5.10.0/lib/sentry/hub.rb:59:in `with_scope'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-5.10.0/lib/sentry-ruby.rb:365:in `with_scope'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/sentry-rails-5.10.0/lib/sentry/rails/active_job.rb:23:in `record'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/sentry-rails-5.10.0/lib/sentry/rails/active_job.rb:8:in `perform_now'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:25:in `block in execute'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/reloader.rb:72:in `block in wrap'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/reloader.rb:71:in `wrap'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `instance_exec'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/execution.rb:23:in `execute'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/activejob-6.1.7.6/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:81:in `block in invoke_job'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/scout_apm-5.3.5/lib/scout_apm/background_job_integrations/delayed_job.rb:71:in `block (3 levels) in install'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block in add'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:78:in `invoke_job'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block (2 levels) in run'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.0/lib/timeout.rb:186:in `block in timeout'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.0/lib/timeout.rb:193:in `timeout'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block in run'
  /home/deploy/.rbenv/versions/3.1.4/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:230:in `run'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `block in reserve_and_run_one_job'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `reserve_and_run_one_job'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:214:in `block in work_off'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `times'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `work_off'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:176:in `block (4 levels) in start'
  /home/deploy/.rbenv/versions/3.1.4/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:175:in `block (3 levels) in start'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:174:in `block (2 levels) in start'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `loop'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `block in start'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block in add'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:172:in `start'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:137:in `run'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:125:in `block in run_process'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/daemons-1.4.1/lib/daemons/application.rb:277:in `block in start_proc'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/daemons-1.4.1/lib/daemons/daemonize.rb:84:in `call_as_daemon'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/daemons-1.4.1/lib/daemons/application.rb:281:in `start_proc'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/daemons-1.4.1/lib/daemons/application.rb:307:in `start'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/daemons-1.4.1/lib/daemons/controller.rb:56:in `run'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/daemons-1.4.1/lib/daemons.rb:199:in `block in run_proc'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/daemons-1.4.1/lib/daemons/cmdline.rb:124:in `catch_exceptions'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/daemons-1.4.1/lib/daemons.rb:198:in `run_proc'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:123:in `run_process'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:104:in `block in daemonize'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:102:in `times'
  /home/deploy/nemo/vendor/bundle/ruby/3.1.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:102:in `daemonize'
  /home/deploy/nemo/bin/delayed_job:5:in `<main>'

-------------------------------
Data:
-------------------------------

  * data: {}

**Comment by cooperka** [comment]
hi @glorykakessa, it's possible this was a recent problem with Twilio's old servers -- can you try again on the latest version 13.26 and see if the same problem occurs?
